#!/bin/bash

# Change to the frontend directory
cd frontend

format_output=$(npm run format-check 2>&1)

# Check the exit code of the previous command
format_exit_code=$?

# Run ESLint
npm run lint

# Capture the exit code of the ESLint command
lint_exit_code=$?

# If the format check produced any output (warnings or errors), exit with an error
if [ $format_exit_code -ne 0 ]; then
  echo "Prettier format check failed. Commit aborted."
  echo "$format_output" # Print the format check output
  exit $format_exit_code
fi

# If ESLint produced any errors, exit with an error
if [ $lint_exit_code -ne 0 ]; then
  echo "ESLint found errors. Commit aborted."
  exit $lint_exit_code
fi

# If we reached this point, both checks passed, so the commit can proceed
exit 0