services:
  backend:
    image: maxidragon/productive-backend:latest
    build:
      context: ./backend
      dockerfile: Dockerfile
    network_mode: host
    restart: unless-stopped
    env_file:
      - .env
