services:
  backend:
    container_name: productivemaster-dev-backend
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    network_mode: host
    volumes:
      - ./backend:/app
    restart: unless-stopped
    labels:
        ofelia.enabled: "true"
        ofelia.job-exec.app.schedule: "@midnight"
        ofelia.job-exec.app.command: "python3 task.py"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: productivemaster-dev-frontend
    volumes:
      - ./frontend/src:/app/src
    ports:
      - "3000:3000"
    restart: unless-stopped

  ofelia:
    image: mcuadros/ofelia:latest
    container_name: productivemaster-dev-ofelia
    restart: always
    depends_on:
      - backend
    command: daemon --docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:r