services:
  backend:
    image: maxidragon/productive-backend:latest
    container_name: productivemaster-prod-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    network_mode: host
    restart: unless-stopped
    env_file:
      - .env
    labels:
      ofelia.enabled: "true"
      ofelia.job-exec.app.schedule: "@midnight"
      ofelia.job-exec.app.command: "python3 task.py"

  ofelia:
    image: mcuadros/ofelia:latest
    container_name: productivemaster-prod-ofelia
    restart: always
    depends_on:
      - backend
    command: daemon --docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:r