# Generated by Django 4.2.5 on 2023-10-04 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_task_completed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='wakatime_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
