# Generated by Django 4.2.5 on 2023-10-04 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_project_wakatime_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='wakatime_name',
        ),
    ]
