# Generated by Django 4.2.5 on 2023-10-16 17:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

def add_people_in_project_to_new_table(apps, schema_editor):
    Project = apps.get_model('tasks', 'Project')
    ProjectUser = apps.get_model('tasks', 'ProjectUser')
    for project in Project.objects.all():
        if project.owner:
            ProjectUser.objects.create(
                project=project,
                user=project.owner,
                is_owner=True,
                added_by=project.owner
            )



class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0009_remove_project_wakatime_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_owner', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='added_project_users', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_users', to='tasks.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunPython(add_people_in_project_to_new_table),
    ]
