# Generated by Django 4.2.5 on 2023-10-16 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_projectuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='owner',
        ),
    ]
