# Generated by Django 4.2.6 on 2023-10-30 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_task_assigne'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='assigne',
            new_name='assignee',
        ),
    ]
