# Generated by Django 4.2.3 on 2023-07-26 16:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('productive', '0002_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='owner',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='goals', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
