# Generated by Django 4.2.3 on 2023-07-31 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productive', '0003_goal_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='github',
            field=models.URLField(blank=True, null=True),
        ),
    ]
