# Generated by Django 4.2.3 on 2023-07-31 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productive', '0005_task_issue'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='pull_request',
            field=models.URLField(blank=True, null=True),
        ),
    ]
