# Generated by Django 4.2.5 on 2023-10-03 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_remove_learningcategory_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learningresource',
            name='description',
        ),
    ]
