# Generated by Django 4.2.5 on 2023-10-04 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_remove_learningresource_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningresource',
            name='url',
            field=models.CharField(max_length=300),
        ),
    ]
