# Generated by Django 4.2.15 on 2024-10-05 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_note_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
