name: Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9]
        node-version: [19.x] 
        
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install frontend dependencies
      run: npm install
      working-directory: 'frontend'
    - name: Build
      run: npm run build
      working-directory: 'frontend'
    - name: Create virtual environment
      run: |
        python3 -m venv venv
        source venv/bin/activate
    - name: Install Dependencies
      working-directory: 'backend' 
      run: |
        python3 -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Create .env
      working-directory: 'backend' 
      run: echo "${{ secrets.ENV_PRODUCTION }}" > .env.production
    - name: Apply migrations
      run: python3 manage.py migrate
    - name: Run app
      working-directory: 'backend' 
      run: |
        nohup python3 manage.py runserver
